name: pino2
favicon: null
layout_spectrum: 0
typography_spectrum: 0.49716
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#485458'
    - '#d4e0e4'
    - '#95a7ad'
    - '#9c6e60'
  brandStrength: 0.375
  lightness: 0.5625
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
